import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export const metadata = {
  title: `Terms of Service`,
  description: `Terms of Service for ${process.env.NEXT_PUBLIC_APP_NAME}, the AI-powered quiz generator for teachers. Governs use of the service, Google Forms integration, and AI-generated content.`,
  alternates: {
    canonical: `${process.env.NEXT_PUBLIC_SITE_URL}/terms`,
  },
};

export default function TermsPage() {
  const appName = process.env.NEXT_PUBLIC_APP_NAME;

  return (
    <div className="min-h-screen bg-white">
      <div className="px-4 lg:px-12 py-12 max-w-xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm text-slate-400 hover:text-slate-600 transition-colors mb-8"
        >
          <ChevronLeft size={14} />
          Back to home
        </Link>

        <h1 className="text-2xl font-semibold text-slate-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-slate-400 mb-8">
          Effective date: March 5, 2026
        </p>

        <div className="space-y-8 text-sm text-slate-600 leading-relaxed">

          {/* 1 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">1. Agreement to Terms</h2>
            <p>
              By accessing or using {appName} (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you are using the Service on behalf of a school, district, or organization, you represent that you have authority to bind that entity to these Terms, and &ldquo;you&rdquo; refers to that entity.
            </p>
            <p>
              If you do not agree to these Terms, you must not access or use the Service.
            </p>
          </section>

          {/* 2 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">2. Description of the Service</h2>
            <p>
              {appName} is a web-based tool that helps educators generate Google Forms quizzes from class content. You provide source material (notes, textbook passages, study guides, etc.), and the Service uses artificial intelligence to generate quiz questions, answer keys, point values, and feedback. Quizzes can be exported directly to your Google Drive as Google Forms.
            </p>
          </section>

          {/* 3 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">3. Access and Authentication</h2>
            <p>
              Access to {appName} requires a valid access key. There are no individual user accounts. By entering an access key, you confirm that you have been authorized to use the Service.
            </p>
            <p>
              You are responsible for keeping your access key confidential. Do not share it with unauthorized individuals. We reserve the right to revoke or deactivate any access key at any time, for any reason, without notice.
            </p>
            <p>
              You are responsible for all activity that occurs using your access key, whether or not you authorized that activity.
            </p>
          </section>

          {/* 4 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">4. Your Content</h2>
            <p>
              &ldquo;Your Content&rdquo; means any text, notes, study materials, or other content you provide to the Service for quiz generation.
            </p>
            <p>
              You retain full ownership of Your Content. By using the Service, you grant us a limited, temporary, non-exclusive license to process Your Content solely for the purpose of generating quiz output. This license terminates immediately upon completion of processing.
            </p>
            <p>
              You represent and warrant that you have all necessary rights to use and submit Your Content, and that Your Content does not infringe the intellectual property rights of any third party. You are solely responsible for ensuring you have permission to use any copyrighted materials you provide.
            </p>
          </section>

          {/* 5 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">5. AI-Generated Output</h2>
            <p>
              Quiz questions, answer keys, point values, and feedback generated by the Service (&ldquo;Generated Output&rdquo;) are produced by artificial intelligence (currently Anthropic&apos;s Claude). You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                Generated Output may contain errors, inaccuracies, or content that is incomplete, misleading, or inappropriate for your intended audience.
              </li>
              <li>
                You are solely responsible for reviewing, verifying, and editing all Generated Output before distributing it to students or using it for grading.
              </li>
              <li>
                The Service does not guarantee that Generated Output will be factually correct, pedagogically sound, or suitable for any particular educational purpose.
              </li>
              <li>
                Generated Output may inadvertently resemble existing copyrighted material. You are responsible for verifying that Generated Output does not infringe third-party intellectual property rights before distributing it.
              </li>
              <li>
                We make no representations regarding the copyright status of Generated Output. Ownership and copyright of AI-generated content may be subject to evolving law in your jurisdiction.
              </li>
            </ul>
          </section>

          {/* 6 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">6. Google Integration</h2>
            <p>
              The Service integrates with Google APIs to create and manage Google Forms on your behalf. When you connect your Google account:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                You authorize {appName} to create Google Forms, enable quiz mode and grading, and organize forms in a designated folder in your Google Drive.
              </li>
              <li>
                The Service requests access to create and edit Google Forms (<code className="text-xs bg-slate-100 px-1 rounded">forms.body</code>) and manage files in your Google Drive (<code className="text-xs bg-slate-100 px-1 rounded">drive.file</code>). No broader access to your Google account is requested or obtained.
              </li>
              <li>
                After initial export, changes you make to a quiz within {appName} will automatically sync to the corresponding Google Form. This sync occurs continuously while you are editing. You can revoke this connection at any time through your{" "}
                <a
                  href="https://myaccount.google.com/permissions"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
                >
                  Google account permissions
                </a>.
              </li>
              <li>
                Your use of Google services is subject to Google&apos;s own{" "}
                <a
                  href="https://developers.google.com/terms"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
                >
                  Terms of Service
                </a>. We are not responsible for changes to Google APIs, outages, or limitations imposed by Google.
              </li>
              <li>
                Google Forms exported from {appName} remain in your Google Drive and are under your control. We do not have ongoing access to forms after export unless you initiate a sync from within the Service.
              </li>
            </ul>
          </section>

          {/* 7 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">7. Third-Party Services</h2>
            <p>
              The Service relies on third-party services to function, including:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                <span className="font-medium text-slate-700">Anthropic API</span> — Your Content is sent to Anthropic&apos;s API for quiz generation. This processing is subject to{" "}
                <a
                  href="https://www.anthropic.com/legal/consumer-terms"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
                >
                  Anthropic&apos;s Terms
                </a>{" "}
                and{" "}
                <a
                  href="https://www.anthropic.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
                >
                  Privacy Policy
                </a>.
              </li>
              <li>
                <span className="font-medium text-slate-700">Google APIs</span> — Used for Google Forms creation and Google Drive file management, as described in Section 6.
              </li>
              <li>
                <span className="font-medium text-slate-700">Vercel</span> — The Service is hosted on Vercel&apos;s infrastructure. Requests are processed through their servers.
              </li>
            </ul>
            <p>
              We are not responsible for the availability, accuracy, or policies of third-party services. Changes to these services may affect the functionality of {appName}.
            </p>
          </section>

          {/* 8 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">8. Data and Privacy</h2>
            <p>
              Our handling of your data is described in our{" "}
              <Link
                href="/privacy"
                className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
              >
                Privacy Policy
              </Link>, which is incorporated into these Terms by reference. Key points:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                Your Content is processed in real time and is not stored on our servers after quiz generation is complete.
              </li>
              <li>
                Quiz data (questions, answers, chat history) is stored locally in your browser. We do not have access to this data.
              </li>
              <li>
                Google authentication tokens are stored in encrypted, HTTP-only cookies and are not persisted in any database.
              </li>
              <li>
                We do not collect personal information, create user profiles, or track usage across sessions.
              </li>
            </ul>
          </section>

          {/* 9 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">9. Acceptable Use</h2>
            <p>
              You agree not to use the Service to:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Generate content that is harmful, abusive, threatening, defamatory, obscene, or otherwise objectionable.</li>
              <li>Generate content designed to harass, discriminate against, or harm students or any individuals.</li>
              <li>Submit content that you do not have the right to use or that infringes third-party intellectual property.</li>
              <li>Attempt to reverse-engineer, decompile, or extract the source code of the Service.</li>
              <li>Interfere with or disrupt the Service, its servers, or connected networks.</li>
              <li>Use automated scripts, bots, or other tools to access the Service at high volume or in a manner that degrades performance for other users.</li>
              <li>Share, resell, or redistribute access keys to unauthorized parties.</li>
              <li>Use the Service for any purpose that violates applicable municipal, provincial, federal, or international law.</li>
            </ul>
            <p>
              We reserve the right to revoke access to anyone who violates these terms, without prior notice.
            </p>
          </section>

          {/* 10 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">10. Intellectual Property</h2>
            <p>
              The Service, including its design, code, interface, and documentation, is owned by {appName} and its operators and is protected by intellectual property laws. These Terms do not grant you any right, title, or interest in the Service beyond the limited right to use it in accordance with these Terms.
            </p>
            <p>
              You may not copy, modify, distribute, sell, or lease any part of the Service, nor may you reverse-engineer or attempt to extract the source code.
            </p>
          </section>

          {/* 11 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">11. Availability and Modifications</h2>
            <p>
              We do not guarantee that the Service will be available at all times or without interruption. We may modify, suspend, or discontinue the Service (or any part of it) at any time, with or without notice.
            </p>
            <p>
              We may update the AI model, change quiz generation behavior, or modify features at any time. We are not obligated to maintain backward compatibility or preserve any specific functionality.
            </p>
          </section>

          {/* 12 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">12. Disclaimer of Warranties</h2>
            <p className="uppercase font-medium text-slate-700 text-xs tracking-wide">
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express, implied, or statutory.
            </p>
            <p>
              To the fullest extent permitted by applicable law, we disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranties arising from course of dealing or usage of trade.
            </p>
            <p>
              Without limiting the foregoing, we do not warrant that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>The Service will meet your requirements or expectations.</li>
              <li>The Service will be uninterrupted, timely, secure, or error-free.</li>
              <li>Generated Output will be accurate, complete, reliable, or suitable for any educational or assessment purpose.</li>
              <li>Any defects in the Service will be corrected.</li>
              <li>The Service will be compatible with any particular educational standards or curricula.</li>
            </ul>
          </section>

          {/* 13 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">13. Limitation of Liability</h2>
            <p className="uppercase font-medium text-slate-700 text-xs tracking-wide">
              To the maximum extent permitted by applicable law, in no event shall {appName}, its operators, affiliates, or service providers be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, or goodwill, arising out of or in connection with your use of (or inability to use) the Service, regardless of the theory of liability and even if we have been advised of the possibility of such damages.
            </p>
            <p>
              This includes, without limitation, damages arising from:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Errors or inaccuracies in Generated Output used in assessments or grading.</li>
              <li>Unauthorized access to or alteration of your data or transmissions.</li>
              <li>Loss of quiz data stored in your browser&apos;s local storage.</li>
              <li>Interruption or failure of Google API integrations.</li>
              <li>Actions taken by third-party services (Anthropic, Google, Vercel).</li>
            </ul>
            <p>
              Our total aggregate liability for all claims arising out of or relating to these Terms or the Service shall not exceed the amount you paid to access the Service in the twelve (12) months preceding the claim, or fifty Canadian dollars (CAD $50), whichever is greater.
            </p>
          </section>

          {/* 14 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">14. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless {appName}, its operators, and affiliates from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Your use of the Service.</li>
              <li>Your Content or any content you distribute that was generated by the Service.</li>
              <li>Your violation of these Terms.</li>
              <li>Your violation of any applicable law or third-party rights.</li>
              <li>Any claim that Your Content infringes the intellectual property rights of a third party.</li>
            </ul>
          </section>

          {/* 15 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">15. Education-Specific Acknowledgments</h2>
            <p>
              If you are using {appName} in an educational setting, you additionally acknowledge that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                The Service is a tool to assist educators, not a replacement for professional educational judgment. You are responsible for ensuring all assessments are appropriate for your students and context.
              </li>
              <li>
                Generated quizzes may not align with specific provincial, board, or institutional standards. You are responsible for reviewing content against applicable curricula and policies.
              </li>
              <li>
                The Service does not collect, process, or store student data. Students do not interact with the Service directly. However, if you include student-identifiable information in Your Content, you do so at your own risk.
              </li>
              <li>
                The Service is not designed to comply with PIPEDA, FIPPA, MFIPPA, or similar privacy and student data protection laws. You are responsible for ensuring your use complies with your institution&apos;s policies and applicable regulations.
              </li>
            </ul>
          </section>

          {/* 16 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">16. Termination</h2>
            <p>
              We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms.
            </p>
            <p>
              Upon termination, your right to use the Service will cease immediately. Quiz data stored in your browser will remain accessible to you locally but will no longer sync with Google Forms. Google Forms previously exported will remain in your Google Drive.
            </p>
            <p>
              Sections 4, 5, 10, 12, 13, 14, 15, and 19 shall survive termination of these Terms.
            </p>
          </section>

          {/* 17 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">17. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated effective date. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms.
            </p>
            <p>
              For material changes, we will make reasonable efforts to provide notice (such as updating the effective date prominently). It is your responsibility to review these Terms periodically.
            </p>
          </section>

          {/* 18 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">18. Contact</h2>
            <p>
              If you have questions about these Terms, you can reach us at{" "}
              <a
                href={`mailto:${process.env.NEXT_PUBLIC_CONTACT_EMAIL}`}
                className="text-slate-700 underline underline-offset-2 hover:text-slate-900"
              >
                {process.env.NEXT_PUBLIC_CONTACT_EMAIL}
              </a>.
            </p>
          </section>

          {/* 19 */}
          <section className="space-y-2">
            <h2 className="text-lg font-medium text-slate-900">19. General Provisions</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <span className="font-medium text-slate-700">Governing law.</span> These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law provisions.
              </li>
              <li>
                <span className="font-medium text-slate-700">Dispute resolution.</span> Any disputes arising under these Terms shall first be subject to good-faith negotiation. If the dispute cannot be resolved within thirty (30) days, it shall be resolved through binding arbitration in accordance with the Arbitration Act, 1991 (Ontario), with the seat of arbitration in Ontario, Canada. You may opt out of this arbitration provision by emailing us at{" "}<a href={`mailto:${process.env.NEXT_PUBLIC_CONTACT_EMAIL}`} className="text-slate-700 underline underline-offset-2 hover:text-slate-900">{process.env.NEXT_PUBLIC_CONTACT_EMAIL}</a>{" "}within thirty (30) days of first accepting these Terms, in which case disputes shall be submitted to the exclusive jurisdiction of the courts of the Province of Ontario.
              </li>
              <li>
                <span className="font-medium text-slate-700">Severability.</span> If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.
              </li>
              <li>
                <span className="font-medium text-slate-700">Entire agreement.</span> These Terms, together with the Privacy Policy, constitute the entire agreement between you and {appName} regarding use of the Service.
              </li>
              <li>
                <span className="font-medium text-slate-700">Waiver.</span> Our failure to enforce any right or provision of these Terms will not be considered a waiver of that right or provision.
              </li>
              <li>
                <span className="font-medium text-slate-700">Assignment.</span> You may not assign or transfer these Terms without our prior written consent. We may assign our rights and obligations without restriction.
              </li>
            </ul>
          </section>

        </div>
      </div>
    </div>
  );
}
